// Centralized mock data for the entire application

// Traces Data
export const TRACES_DATA = [
  {
    id: "tr_cs_001",
    name: "Customer Support - Login Issue",
    timestamp: "2024-01-15 14:23:45",
    status: "success",
    latency: "1.2s",
    tokens: 445,
    cost: "$0.0022",
    model: "gpt-4",
    user: "user_12345",
    tags: ["support", "authentication"],
    input: "User cannot log in with error 403",
    output: "Provided password reset link and troubleshooting steps",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "us-east-1",
  },
  {
    id: "tr_cs_002",
    name: "Customer Support - Billing Query",
    timestamp: "2024-01-15 14:18:32",
    status: "success",
    latency: "1.1s",
    tokens: 432,
    cost: "$0.0021",
    model: "gpt-4",
    user: "user_67890",
    tags: ["support", "billing"],
    input: "Explain the charge on my credit card",
    output: "Breakdown of monthly subscription fees provided",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "us-east-1",
  },
  {
    id: "tr_code_001",
    name: "Code Generation - React Component",
    timestamp: "2024-01-15 14:15:20",
    status: "success",
    latency: "2.3s",
    tokens: 892,
    cost: "$0.0051",
    model: "gpt-4",
    user: "dev_user_001",
    tags: ["development", "react"],
    input: "Create a responsive navbar component",
    output: "```tsx\nexport const Navbar = () => { ... }```",
    environment: "staging",
    cloudProvider: "gcp",
    cloudRegion: "us-central1",
  },
  {
    id: "tr_code_002",
    name: "Code Generation - API Endpoint",
    timestamp: "2024-01-15 14:10:15",
    status: "success",
    latency: "2.1s",
    tokens: 756,
    cost: "$0.0043",
    model: "gpt-4",
    user: "dev_user_002",
    tags: ["development", "api"],
    input: "FastAPI endpoint for user registration",
    output: "```python\n@app.post('/register')\ndef register(): ...```",
    environment: "development",
    cloudProvider: "gcp",
    cloudRegion: "us-central1",
  },
  {
    id: "tr_sum_001",
    name: "Document Summarization - Legal Contract",
    timestamp: "2024-01-15 14:05:10",
    status: "success",
    latency: "1.8s",
    tokens: 634,
    cost: "$0.0036",
    model: "gpt-4",
    user: "analyst_001",
    tags: ["analysis", "legal"],
    input: "Summarize this NDA agreement...",
    output: " key terms: confidentiality duration, exclusions...",
    environment: "production",
    cloudProvider: "azure",
    cloudRegion: "eastus",
  },
  {
    id: "tr_sum_002",
    name: "Document Summarization - Research Paper",
    timestamp: "2024-01-15 13:58:45",
    status: "success",
    latency: "1.7s",
    tokens: 612,
    cost: "$0.0035",
    model: "gpt-4",
    user: "analyst_002",
    tags: ["analysis", "research"],
    input: "Abstract of Attention Is All You Need",
    output: "Introduction of Transformer architecture...",
    environment: "production",
    cloudProvider: "azure",
    cloudRegion: "eastus",
  },
  {
    id: "tr_sent_001",
    name: "Sentiment Analysis - Product Review",
    timestamp: "2024-01-15 13:52:30",
    status: "success",
    latency: "0.9s",
    tokens: 278,
    cost: "$0.0016",
    model: "gpt-3.5-turbo",
    user: "analyst_003",
    tags: ["analysis", "sentiment"],
    input: "The battery life is terrible but screen is great",
    output: "Sentiment: Mixed (Negative leaning)",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "eu-west-1",
  },
  {
    id: "tr_sent_002",
    name: "Sentiment Analysis - Customer Feedback",
    timestamp: "2024-01-15 13:45:20",
    status: "success",
    latency: "0.8s",
    tokens: 265,
    cost: "$0.0015",
    model: "gpt-3.5-turbo",
    user: "analyst_004",
    tags: ["analysis", "sentiment"],
    input: "Best service I have ever received!",
    output: "Sentiment: Positive",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "eu-west-1",
  },
  {
    id: "tr_email_001",
    name: "Email Draft - Partnership Proposal",
    timestamp: "2024-01-15 13:38:15",
    status: "warning",
    latency: "1.6s",
    tokens: 534,
    cost: "$0.0030",
    model: "gpt-4",
    user: "comm_user_001",
    tags: ["communication", "business"],
    input: "Draft email to Acme Corp about collaboration",
    output: "Subject: Strategic Partnership Opportunity...",
    environment: "staging",
    cloudProvider: "aws",
    cloudRegion: "us-west-2",
  },
  {
    id: "tr_data_001",
    name: "Data Extraction - Invoice Processing",
    timestamp: "2024-01-15 13:30:10",
    status: "success",
    latency: "1.3s",
    tokens: 389,
    cost: "$0.0022",
    model: "gpt-4",
    user: "proc_user_001",
    tags: ["processing", "finance"],
    input: "Extract total amount and date from text",
    output: "{ total: 1250.00, date: '2023-12-20' }",
    environment: "production",
    cloudProvider: "gcp",
    cloudRegion: "europe-west1",
  },
  // New Traces
  {
    id: "tr_err_001",
    name: "Payment Gateway Integration",
    timestamp: "2024-01-15 13:25:00",
    status: "error",
    latency: "5.4s",
    tokens: 120,
    cost: "$0.0008",
    model: "gpt-4",
    user: "sys_admin",
    tags: ["payment", "error"],
    input: "Process payment for order #9988",
    output: "Error: Connection timeout to Stripe API",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "us-east-1",
  },
  {
    id: "tr_rag_001",
    name: "Knowledge Base Retrieval",
    timestamp: "2024-01-15 13:20:15",
    status: "success",
    latency: "3.2s",
    tokens: 1450,
    cost: "$0.0085",
    model: "gpt-4-turbo",
    user: "support_Lead",
    tags: ["rag", "internal"],
    input: "What is the policy on remote work equipment?",
    output: "Employees are eligible for a $500 stipend...",
    environment: "production",
    cloudProvider: "azure",
    cloudRegion: "westus",
  },
  {
    id: "tr_sec_001",
    name: "Security Audit Log Analysis",
    timestamp: "2024-01-15 13:15:30",
    status: "success",
    latency: "4.1s",
    tokens: 2100,
    cost: "$0.0120",
    model: "gpt-4",
    user: "sec_ops",
    tags: ["security", "audit"],
    input: "Analyze these logs for suspicious activity",
    output: "No critical threats detected. 2 low severity warnings.",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "us-east-1",
  },
  {
    id: "tr_trans_001",
    name: "Translation - Marketing Copy",
    timestamp: "2024-01-15 13:10:05",
    status: "success",
    latency: "1.5s",
    tokens: 560,
    cost: "$0.0032",
    model: "gpt-4",
    user: "marketing_global",
    tags: ["translation", "marketing"],
    input: "Translate to Spanish: 'Unlock your potential'",
    output: "'Desbloquea tu potencial'",
    environment: "staging",
    cloudProvider: "gcp",
    cloudRegion: "asia-northeast1",
  },
  {
    id: "tr_sql_001",
    name: "Text to SQL - Analytics",
    timestamp: "2024-01-15 13:05:20",
    status: "warning",
    latency: "2.8s",
    tokens: 450,
    cost: "$0.0028",
    model: "gpt-3.5-turbo",
    user: "data_analyst",
    tags: ["sql", "analytics"],
    input: "Show me top 5 users by spend in last week",
    output: "SELECT user_id, SUM(amount) ... LIMIT 5",
    environment: "development",
    cloudProvider: "aws",
    cloudRegion: "us-east-2",
  },
  {
    id: "tr_chat_001",
    name: "General Chat - Creative Writing",
    timestamp: "2024-01-15 13:00:10",
    status: "success",
    latency: "6.2s",
    tokens: 3200,
    cost: "$0.0180",
    model: "gpt-4",
    user: "creative_writer",
    tags: ["creative", "writing"],
    input: "Write a sci-fi story about a time traveling toaster",
    output: "In the year 2305, the Chromium 5000 toaster...",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "us-west-1",
  },
  {
    id: "tr_class_001",
    name: "Ticket Classification",
    timestamp: "2024-01-15 12:55:00",
    status: "success",
    latency: "0.5s",
    tokens: 150,
    cost: "$0.0008",
    model: "gpt-3.5-turbo",
    user: "support_bot",
    tags: ["classification", "automation"],
    input: "My internet is down",
    output: "Category: Technical Support / Connectivity",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "eu-central-1",
  },
  {
    id: "tr_sum_003",
    name: "Meeting Transcription Summary",
    timestamp: "2024-01-15 12:50:45",
    status: "success",
    latency: "3.5s",
    tokens: 1800,
    cost: "$0.0105",
    model: "claude-3-sonnet",
    user: "pm_user",
    tags: ["summary", "meeting"],
    input: "Summarize the key decisions from this transcript",
    output: "1. Launch date confirmed for Q3...",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "us-east-1",
  },
  {
    id: "tr_img_001",
    name: "Image Captioning",
    timestamp: "2024-01-15 12:45:30",
    status: "success",
    latency: "2.8s",
    tokens: 120,
    cost: "$0.0040",
    model: "gpt-4-vision",
    user: "content_mod",
    tags: ["vision", "caption"],
    input: "[Image Upload]",
    output: "A happy family playing in a park at sunset",
    environment: "staging",
    cloudProvider: "azure",
    cloudRegion: "eastus2",
  },
  {
    id: "tr_code_003",
    name: "Code Refactoring - Legacy Java",
    timestamp: "2024-01-15 12:40:15",
    status: "error",
    latency: "8.5s",
    tokens: 4500,
    cost: "$0.0520",
    model: "gpt-4",
    user: "senior_dev",
    tags: ["development", "refactoring"],
    input: "Refactor this 2000 line class to patterns",
    output: "Error: Context window exceeded",
    environment: "development",
    cloudProvider: "gcp",
    cloudRegion: "us-west1",
  },
  {
    id: "tr_rag_002",
    name: "Medical Policy Q&A",
    timestamp: "2024-01-15 12:35:00",
    status: "success",
    latency: "2.9s",
    tokens: 950,
    cost: "$0.0055",
    model: "gpt-4",
    user: "health_admin",
    tags: ["rag", "medical"],
    input: "Is procedure 99213 covered?",
    output: "Yes, under general outpatient services...",
    environment: "production",
    cloudProvider: "azure",
    cloudRegion: "centralus",
  },
  {
    id: "tr_fin_001",
    name: "Financial Report Analysis",
    timestamp: "2024-01-15 12:30:10",
    status: "warning",
    latency: "3.1s",
    tokens: 1100,
    cost: "$0.0062",
    model: "gpt-4",
    user: "cfo_office",
    tags: ["finance", "analysis"],
    input: "Identify risks in Q4 report",
    output: "Potential liquidity issues noted in...",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "us-east-1",
  },
  {
    id: "tr_auth_001",
    name: "Auth Service - OAuth Flow",
    timestamp: "2024-01-15 12:20:00",
    status: "success",
    latency: "0.8s",
    tokens: 150,
    cost: "$0.0005",
    model: "gpt-3.5-turbo",
    user: "user_new_01",
    tags: ["auth", "oauth"],
    input: "Validate OAuth token from Provider X",
    output: "Token valid. Scopes: [profile, email]",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "us-east-1",
  },
  {
    id: "tr_auth_002",
    name: "Auth Service - Invalid Token",
    timestamp: "2024-01-15 12:18:30",
    status: "error",
    latency: "0.3s",
    tokens: 80,
    cost: "$0.0002",
    model: "gpt-3.5-turbo",
    user: "user_malicious",
    tags: ["auth", "security"],
    input: "Validate token: eyJhbGciOi...",
    output: "Error: Signature verification failed",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "us-east-1",
  },
  {
    id: "tr_rec_001",
    name: "Recommendation - Movie Suggestions",
    timestamp: "2024-01-15 12:15:45",
    status: "success",
    latency: "1.5s",
    tokens: 580,
    cost: "$0.0020",
    model: "gpt-4",
    user: "viewer_88",
    tags: ["recommendation", "entertainment"],
    input: "Suggest movies like Inception",
    output: "1. Tenet\n2. Interstellar\n3. The Matrix",
    environment: "production",
    cloudProvider: "gcp",
    cloudRegion: "us-central1",
  },
  {
    id: "tr_rec_002",
    name: "Recommendation - Product Upsell",
    timestamp: "2024-01-15 12:12:10",
    status: "success",
    latency: "0.9s",
    tokens: 320,
    cost: "$0.0012",
    model: "gpt-3.5-turbo",
    user: "shopper_99",
    tags: ["recommendation", "ecommerce"],
    input: "User bought Laptop. Suggest accessories.",
    output: "Mouse, Laptop Stand, USB-C Hub",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "eu-west-1",
  },
  {
    id: "tr_rec_003",
    name: "Recommendation - Cold Start",
    timestamp: "2024-01-15 12:10:05",
    status: "warning",
    latency: "0.4s",
    tokens: 150,
    cost: "$0.0005",
    model: "gpt-3.5-turbo",
    user: "guest_user",
    tags: ["recommendation", "cold-start"],
    input: "Recommend trending items for guest",
    output: "Fallback to global top 10 list",
    environment: "staging",
    cloudProvider: "azure",
    cloudRegion: "eastus",
  },
  {
    id: "tr_search_001",
    name: "Semantic Search - 'Red shoes'",
    timestamp: "2024-01-15 12:08:20",
    status: "success",
    latency: "0.5s",
    tokens: 60,
    cost: "$0.0001",
    model: "text-embedding-3-small",
    user: "shopper_33",
    tags: ["search", "embedding"],
    input: "red shoes cheap running",
    output: "Vector: [0.12, -0.05, 0.88...]",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "us-east-1",
  },
  {
    id: "tr_search_002",
    name: "Semantic Search - 'Quantum physics'",
    timestamp: "2024-01-15 12:06:15",
    status: "success",
    latency: "0.6s",
    tokens: 75,
    cost: "$0.0001",
    model: "text-embedding-3-large",
    user: "student_01",
    tags: ["search", "embedding"],
    input: "basics of quantum mechanics",
    output: "Vector: [-0.02, 0.45, 0.11...]",
    environment: "production",
    cloudProvider: "gcp",
    cloudRegion: "us-central1",
  },
  {
    id: "tr_search_003",
    name: "Semantic Search - Zero Results",
    timestamp: "2024-01-15 12:04:30",
    status: "warning",
    latency: "0.3s",
    tokens: 40,
    cost: "$0.0001",
    model: "text-embedding-3-small",
    user: "tester_02",
    tags: ["search", "edge-case"],
    input: "kjsdhfksjdhf",
    output: "Vector generated but no DB matches found",
    environment: "staging",
    cloudProvider: "aws",
    cloudRegion: "us-west-2",
  },
  {
    id: "tr_inv_001",
    name: "Inventory Check - SKU 123",
    timestamp: "2024-01-15 12:02:10",
    status: "success",
    latency: "0.2s",
    tokens: 45,
    cost: "$0.0001",
    model: "gpt-3.5-turbo",
    user: "warehouse_bot",
    tags: ["inventory", "internal"],
    input: "Check stock for SKU-123",
    output: "Available: 4500 units",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "us-east-1",
  },
  {
    id: "tr_inv_002",
    name: "Inventory Check - SKU 456",
    timestamp: "2024-01-15 12:00:05",
    status: "success",
    latency: "0.2s",
    tokens: 45,
    cost: "$0.0001",
    model: "gpt-3.5-turbo",
    user: "warehouse_bot",
    tags: ["inventory", "internal"],
    input: "Check stock for SKU-456",
    output: "Available: 12 units (Low Stock)",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "us-east-1",
  },
  {
    id: "tr_inv_003",
    name: "Inventory Check - Timeout",
    timestamp: "2024-01-15 11:58:00",
    status: "error",
    latency: "5.0s",
    tokens: 30,
    cost: "$0.0001",
    model: "gpt-3.5-turbo",
    user: "warehouse_bot",
    tags: ["inventory", "error"],
    input: "Check stock for SKU-999",
    output: "Error: DB Connection Timeout",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "us-east-1",
  },
  {
    id: "tr_cart_001",
    name: "Shopping Cart - Add Item",
    timestamp: "2024-01-15 11:55:20",
    status: "success",
    latency: "0.5s",
    tokens: 120,
    cost: "$0.0004",
    model: "gpt-3.5-turbo",
    user: "shopper_55",
    tags: ["cart", "ecommerce"],
    input: "Add product 55 to cart. Confirm total.",
    output: "Added. Cart Total: $45.99",
    environment: "production",
    cloudProvider: "azure",
    cloudRegion: "eastus",
  },
  {
    id: "tr_cart_002",
    name: "Shopping Cart - Remove Item",
    timestamp: "2024-01-15 11:53:15",
    status: "success",
    latency: "0.4s",
    tokens: 110,
    cost: "$0.0003",
    model: "gpt-3.5-turbo",
    user: "shopper_55",
    tags: ["cart", "ecommerce"],
    input: "Remove product 55 from cart.",
    output: "Removed. Cart Empty.",
    environment: "production",
    cloudProvider: "azure",
    cloudRegion: "eastus",
  },
  {
    id: "tr_checkout_001",
    name: "Checkout - Payment Process",
    timestamp: "2024-01-15 11:50:00",
    status: "success",
    latency: "2.1s",
    tokens: 300,
    cost: "$0.0015",
    model: "gpt-4",
    user: "shopper_22",
    tags: ["checkout", "payment"],
    input: "Process Visa ending 4242 for $99.00",
    output: "Transaction Authorized. Ref: #TXN-7788",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "us-east-1",
  },
  {
    id: "tr_checkout_002",
    name: "Checkout - Fraud Alert",
    timestamp: "2024-01-15 11:48:30",
    status: "warning",
    latency: "1.2s",
    tokens: 250,
    cost: "$0.0012",
    model: "gpt-4",
    user: "shopper_suspicious",
    tags: ["checkout", "security"],
    input: "Process huge order to non-matching address",
    output: "Flagged for manual review. High risk score.",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "us-east-1",
  },
  {
    id: "tr_checkout_003",
    name: "Checkout - Card Declined",
    timestamp: "2024-01-15 11:46:10",
    status: "error",
    latency: "0.8s",
    tokens: 180,
    cost: "$0.0008",
    model: "gpt-3.5-turbo",
    user: "shopper_broke",
    tags: ["checkout", "error"],
    input: "Process payment",
    output: "Error: Insufficient Funds",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "us-east-1",
  },
  {
    id: "tr_onboard_001",
    name: "Onboarding - Profile Creation",
    timestamp: "2024-01-15 11:40:00",
    status: "success",
    latency: "1.8s",
    tokens: 450,
    cost: "$0.0018",
    model: "gpt-4",
    user: "new_joiner_01",
    tags: ["onboarding", "user-mgmt"],
    input: "Create profile for John Doe, Engineer",
    output: "Profile created. Role assigned: Engineer.",
    environment: "staging",
    cloudProvider: "gcp",
    cloudRegion: "europe-west1",
  },
  {
    id: "tr_onboard_002",
    name: "Onboarding - Email Verify",
    timestamp: "2024-01-15 11:38:20",
    status: "success",
    latency: "0.5s",
    tokens: 120,
    cost: "$0.0004",
    model: "gpt-3.5-turbo",
    user: "new_joiner_01",
    tags: ["onboarding", "email"],
    input: "Send verification email",
    output: "Email sent to john.doe@example.com",
    environment: "staging",
    cloudProvider: "aws",
    cloudRegion: "us-east-1",
  },
  {
    id: "tr_dash_001",
    name: "Dashboard - Load Analytics",
    timestamp: "2024-01-15 11:30:15",
    status: "success",
    latency: "3.5s",
    tokens: 1500,
    cost: "$0.0075",
    model: "gpt-4-turbo",
    user: "admin_01",
    tags: ["dashboard", "analytics"],
    input: "Summarize last week's traffic trends",
    output: "Traffic up 20%. Peak on Tuesday...",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "us-west-2",
  },
  {
    id: "tr_dash_002",
    name: "Dashboard - Realtime Feed",
    timestamp: "2024-01-15 11:28:10",
    status: "success",
    latency: "0.9s",
    tokens: 200,
    cost: "$0.0010",
    model: "gpt-3.5-turbo",
    user: "admin_01",
    tags: ["dashboard", "realtime"],
    input: "Fetch latest 5 events",
    output: "Events: [Login, Logout, Purchase, ...]",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "us-west-2",
  },
  {
    id: "tr_dash_003",
    name: "Dashboard - Export Report",
    timestamp: "2024-01-15 11:25:00",
    status: "success",
    latency: "8.2s",
    tokens: 5200,
    cost: "$0.0450",
    model: "gpt-4",
    user: "exec_05",
    tags: ["dashboard", "export"],
    input: "Generate PDF report for Q3",
    output: "Report generated. Link: /reports/q3_2023.pdf",
    environment: "production",
    cloudProvider: "azure",
    cloudRegion: "eastus",
  },
  {
    id: "tr_rep_001",
    name: "Report Gen - Monthly",
    timestamp: "2024-01-15 11:20:00",
    status: "success",
    latency: "12.5s",
    tokens: 8500,
    cost: "$0.0800",
    model: "claude-3-opus",
    user: "analyst_hq",
    tags: ["reporting", "batch"],
    input: "Analyze all sales data for January",
    output: "Comprehensive breakdown: North region led...",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "us-east-1",
  },
  {
    id: "tr_rep_002",
    name: "Report Gen - Quarterly",
    timestamp: "2024-01-15 11:15:00",
    status: "success",
    latency: "25.0s",
    tokens: 15000,
    cost: "$0.1500",
    model: "claude-3-opus",
    user: "analyst_hq",
    tags: ["reporting", "batch"],
    input: "Analyze Q4 performance vs Q3",
    output: "Growth observed in 3/4 sectors...",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "us-east-1",
  },
  {
    id: "tr_rep_003",
    name: "Report Gen - Yearly Error",
    timestamp: "2024-01-15 11:10:00",
    status: "error",
    latency: "45.0s",
    tokens: 32000,
    cost: "$0.3200",
    model: "gpt-4-32k",
    user: "analyst_hq",
    tags: ["reporting", "error"],
    input: "Process full year transaction logs",
    output: "Error: Output token limit exceeded",
    environment: "production",
    cloudProvider: "aws",
    cloudRegion: "us-east-1",
  },
  {
    id: "tr_alert_001",
    name: "System Alert - CPU Spike",
    timestamp: "2024-01-15 11:05:00",
    status: "success",
    latency: "1.0s",
    tokens: 150,
    cost: "$0.0005",
    model: "gpt-3.5-turbo",
    user: "system_monitor",
    tags: ["ops", "alert"],
    input: "Analyze metrics: CPU > 90% for 5 mins",
    output: "Diagnosis: Likely garbage collection process",
    environment: "production",
    cloudProvider: "gcp",
    cloudRegion: "us-central1",
  },
];

// Observations Data
export const OBSERVATIONS_DATA = [
  // Existing Observations (Refined)
  {
    id: "obs-001",
    timestamp: "2024-01-15 10:23:45",
    name: "LLM Generation - GPT-4",
    type: "GENERATION",
    latency: "1.2s",
    cost: "$0.0023",
    traceId: "tr_cs_001",
  },
  {
    id: "obs-002",
    timestamp: "2024-01-15 10:23:44",
    name: "Embedding - User Query",
    type: "EMBEDDING",
    latency: "0.3s",
    cost: "$0.0001",
    traceId: "tr_cs_001",
  },
  {
    id: "obs-003",
    timestamp: "2024-01-15 10:23:42",
    name: "Vector Search - Knowledge Base",
    type: "SPAN",
    latency: "0.5s",
    cost: "-",
    traceId: "tr_cs_001",
  },
  {
    id: "obs-004",
    timestamp: "2024-01-15 10:22:15",
    name: "Chat Completion",
    type: "GENERATION",
    latency: "2.1s",
    cost: "$0.0045",
    traceId: "tr_code_001",
  },
  {
    id: "obs-005",
    timestamp: "2024-01-15 10:21:30",
    name: "Tool Call - Search Docs",
    type: "SPAN",
    latency: "0.8s",
    cost: "-",
    traceId: "tr_code_002",
  },
  {
    id: "obs-006",
    timestamp: "2024-01-15 10:20:10",
    name: "Retrieval - Vector DB",
    type: "SPAN",
    latency: "1.1s",
    cost: "$0.0005",
    traceId: "tr_rag_001",
  },
  {
    id: "obs-007",
    timestamp: "2024-01-15 10:20:12",
    name: "Reranking - Cohere",
    type: "SPAN",
    latency: "0.4s",
    cost: "$0.0002",
    traceId: "tr_rag_001",
  },
  {
    id: "obs-008",
    timestamp: "2024-01-15 10:19:55",
    name: "SQL Generation",
    type: "GENERATION",
    latency: "1.5s",
    cost: "$0.0012",
    traceId: "tr_sql_001",
  },
  {
    id: "obs-009",
    timestamp: "2024-01-15 10:18:30",
    name: "Vision Encoder",
    type: "MODEL",
    latency: "2.5s",
    cost: "$0.0035",
    traceId: "tr_img_001",
  },
  {
    id: "obs-010",
    timestamp: "2024-01-15 10:17:15",
    name: "Guardrail Check - Input",
    type: "SPAN",
    latency: "0.2s",
    cost: "-",
    traceId: "tr_chat_001",
  },
  // New Observations for New Traces
  {
    id: "obs-011",
    timestamp: "2024-01-15 12:20:00",
    name: "Token Validation",
    type: "SPAN",
    latency: "0.4s",
    cost: "-",
    traceId: "tr_auth_001",
  },
  {
    id: "obs-012",
    timestamp: "2024-01-15 12:20:01",
    name: "Scope Check",
    type: "SPAN",
    latency: "0.1s",
    cost: "-",
    traceId: "tr_auth_001",
  },
  {
    id: "obs-013",
    timestamp: "2024-01-15 12:18:30",
    name: "Signature Verification",
    type: "SPAN",
    latency: "0.2s",
    cost: "-",
    traceId: "tr_auth_002",
  },
  {
    id: "obs-014",
    timestamp: "2024-01-15 12:15:45",
    name: "User History Retrieval",
    type: "SPAN",
    latency: "0.3s",
    cost: "-",
    traceId: "tr_rec_001",
  },
  {
    id: "obs-015",
    timestamp: "2024-01-15 12:15:47",
    name: "LLM Recommendation",
    type: "GENERATION",
    latency: "1.1s",
    cost: "$0.0020",
    traceId: "tr_rec_001",
  },
  {
    id: "obs-016",
    timestamp: "2024-01-15 12:08:20",
    name: "Embedding Generation",
    type: "EMBEDDING",
    latency: "0.2s",
    cost: "$0.0001",
    traceId: "tr_search_001",
  },
  {
    id: "obs-017",
    timestamp: "2024-01-15 12:08:21",
    name: "Pinecone Query",
    type: "SPAN",
    latency: "0.3s",
    cost: "-",
    traceId: "tr_search_001",
  },
  {
    id: "obs-018",
    timestamp: "2024-01-15 12:04:30",
    name: "Embedding Generation",
    type: "EMBEDDING",
    latency: "0.2s",
    cost: "$0.0001",
    traceId: "tr_search_003",
  },
  {
    id: "obs-019",
    timestamp: "2024-01-15 12:04:31",
    name: "Empty Result Handler",
    type: "SPAN",
    latency: "0.1s",
    cost: "-",
    traceId: "tr_search_003",
  },
  {
    id: "obs-020",
    timestamp: "2024-01-15 11:58:00",
    name: "DB Select Query",
    type: "SPAN",
    latency: "5.0s",
    cost: "-",
    traceId: "tr_inv_003",
  },
  {
    id: "obs-021",
    timestamp: "2024-01-15 11:50:00",
    name: "Payment Gateway API",
    type: "SPAN",
    latency: "1.8s",
    cost: "-",
    traceId: "tr_checkout_001",
  },
  {
    id: "obs-022",
    timestamp: "2024-01-15 11:48:30",
    name: "Risk Analysis Model",
    type: "MODEL",
    latency: "0.9s",
    cost: "$0.0005",
    traceId: "tr_checkout_002",
  },
  {
    id: "obs-023",
    timestamp: "2024-01-15 11:30:15",
    name: "Analytics Aggregation",
    type: "SPAN",
    latency: "2.0s",
    cost: "-",
    traceId: "tr_dash_001",
  },
  {
    id: "obs-024",
    timestamp: "2024-01-15 11:30:17",
    name: "Summary Generation",
    type: "GENERATION",
    latency: "1.4s",
    cost: "$0.0075",
    traceId: "tr_dash_001",
  },
  {
    id: "obs-025",
    timestamp: "2024-01-15 11:20:00",
    name: "Data Fetching (Batch)",
    type: "SPAN",
    latency: "4.0s",
    cost: "-",
    traceId: "tr_rep_001",
  },
  {
    id: "obs-026",
    timestamp: "2024-01-15 11:20:05",
    name: "Report Synthesis (Claude)",
    type: "GENERATION",
    latency: "8.0s",
    cost: "$0.0800",
    traceId: "tr_rep_001",
  },
  {
    id: "obs-027",
    timestamp: "2024-01-15 11:10:00",
    name: "Data Fetching (Full Year)",
    type: "SPAN",
    latency: "15.0s",
    cost: "-",
    traceId: "tr_rep_003",
  },
  {
    id: "obs-028",
    timestamp: "2024-01-15 11:10:15",
    name: "Processing Loop",
    type: "SPAN",
    latency: "20.0s",
    cost: "-",
    traceId: "tr_rep_003",
  },
  {
    id: "obs-029",
    timestamp: "2024-01-15 11:10:35",
    name: "OOM Error Catch",
    type: "SPAN",
    latency: "0.1s",
    cost: "-",
    traceId: "tr_rep_003",
  },
  {
    id: "obs-030",
    timestamp: "2024-01-15 11:05:00",
    name: "Metric Scraper",
    type: "SPAN",
    latency: "0.5s",
    cost: "-",
    traceId: "tr_alert_001",
  },
  {
    id: "obs-031",
    timestamp: "2024-01-15 11:05:01",
    name: "Root Cause Analysis",
    type: "GENERATION",
    latency: "0.5s",
    cost: "$0.0005",
    traceId: "tr_alert_001",
  },
  {
    id: "obs-032",
    timestamp: "2024-01-15 13:25:00",
    name: "Stripe API Handshake",
    type: "SPAN",
    latency: "0.2s",
    cost: "-",
    traceId: "tr_err_001",
  },
  {
    id: "obs-033",
    timestamp: "2024-01-15 13:25:01",
    name: "Payment Execution",
    type: "SPAN",
    latency: "5.0s",
    cost: "-",
    traceId: "tr_err_001",
  },
  {
    id: "obs-034",
    timestamp: "2024-01-15 13:15:30",
    name: "Log Ingestion",
    type: "SPAN",
    latency: "2.0s",
    cost: "-",
    traceId: "tr_sec_001",
  },
  {
    id: "obs-035",
    timestamp: "2024-01-15 13:15:33",
    name: "Threat Detection Model",
    type: "MODEL",
    latency: "2.0s",
    cost: "$0.0120",
    traceId: "tr_sec_001",
  },
  {
    id: "obs-036",
    timestamp: "2024-01-15 13:10:05",
    name: "Translation Model",
    type: "GENERATION",
    latency: "1.4s",
    cost: "$0.0032",
    traceId: "tr_trans_001",
  },
  {
    id: "obs-037",
    timestamp: "2024-01-15 12:45:30",
    name: "Image Preprocessing",
    type: "SPAN",
    latency: "0.5s",
    cost: "-",
    traceId: "tr_img_001",
  },
  {
    id: "obs-038",
    timestamp: "2024-01-15 12:40:15",
    name: "Code Analysis",
    type: "MEASURE",
    latency: "2.0s",
    cost: "-",
    traceId: "tr_code_003",
  },
  {
    id: "obs-039",
    timestamp: "2024-01-15 12:40:18",
    name: "Refactoring Request",
    type: "GENERATION",
    latency: "6.0s",
    cost: "$0.0520",
    traceId: "tr_code_003",
  },
  {
    id: "obs-040",
    timestamp: "2024-01-15 12:35:00",
    name: "Medical KB Lookup",
    type: "SPAN",
    latency: "1.0s",
    cost: "$0.0010",
    traceId: "tr_rag_002",
  },
  {
    id: "obs-041",
    timestamp: "2024-01-15 12:35:02",
    name: "Answer Synthesis",
    type: "GENERATION",
    latency: "1.8s",
    cost: "$0.0045",
    traceId: "tr_rag_002",
  },
  {
    id: "obs-042",
    timestamp: "2024-01-15 12:30:10",
    name: "Financial Data Tool",
    type: "SPAN",
    latency: "1.5s",
    cost: "-",
    traceId: "tr_fin_001",
  },
  {
    id: "obs-043",
    timestamp: "2024-01-15 12:30:12",
    name: "Risk Assessment",
    type: "GENERATION",
    latency: "1.5s",
    cost: "$0.0062",
    traceId: "tr_fin_001",
  },
  {
    id: "obs-044",
    timestamp: "2024-01-15 11:40:02",
    name: "Database Insert",
    type: "SPAN",
    latency: "0.2s",
    cost: "-",
    traceId: "tr_onboard_001",
  },
  {
    id: "obs-045",
    timestamp: "2024-01-15 11:38:21",
    name: "SMTP Send",
    type: "SPAN",
    latency: "0.3s",
    cost: "-",
    traceId: "tr_onboard_002",
  },
  {
    id: "obs-046",
    timestamp: "2024-01-15 12:12:10",
    name: "User Purchase History",
    type: "SPAN",
    latency: "0.2s",
    cost: "-",
    traceId: "tr_rec_002",
  },
  {
    id: "obs-047",
    timestamp: "2024-01-15 12:12:11",
    name: "Upsell Model",
    type: "GENERATION",
    latency: "0.7s",
    cost: "$0.0012",
    traceId: "tr_rec_002",
  },
  {
    id: "obs-048",
    timestamp: "2024-01-15 12:10:05",
    name: "Guest Session Check",
    type: "SPAN",
    latency: "0.1s",
    cost: "-",
    traceId: "tr_rec_003",
  },
  {
    id: "obs-049",
    timestamp: "2024-01-15 12:06:15",
    name: "Knowledge Graph Lookup",
    type: "SPAN",
    latency: "0.4s",
    cost: "-",
    traceId: "tr_search_002",
  },
  {
    id: "obs-050",
    timestamp: "2024-01-15 12:06:16",
    name: "Embedding - Large",
    type: "EMBEDDING",
    latency: "0.2s",
    cost: "$0.0001",
    traceId: "tr_search_002",
  },
];

// Prompts Data
export const PROMPTS_DATA = [
  {
    id: "prompt-001",
    name: "Customer Support Response",
    agentName: "Support Agent",
    traceId: "tr_cs_001",
    category: "Support",
    effectiveness: 0.94,
    avgLatency: "1.2s",
    avgTokens: 445,
    avgCost: "$0.0023",
    executions: 15420,
    lastUsed: "2 min ago",
    trend: "up" as const,
    pattern: "high-performer" as const,
  },
  {
    id: "prompt-002",
    name: "Code Generation Assistant",
    agentName: "Dev Agent",
    traceId: "tr_code_001",
    category: "Development",
    effectiveness: 0.88,
    avgLatency: "2.1s",
    avgTokens: 780,
    avgCost: "$0.0045",
    executions: 8920,
    lastUsed: "5 min ago",
    trend: "stable" as const,
    pattern: "standard" as const,
  },
  {
    id: "prompt-003",
    name: "Document Summarization",
    agentName: "Analysis Agent",
    traceId: "tr_sum_001",
    category: "Analysis",
    effectiveness: 0.91,
    avgLatency: "1.8s",
    avgTokens: 620,
    avgCost: "$0.0034",
    executions: 12350,
    lastUsed: "10 min ago",
    trend: "up" as const,
    pattern: "high-performer" as const,
  },
  {
    id: "prompt-004",
    name: "Sentiment Analysis",
    agentName: "Analysis Agent",
    traceId: "tr_sent_001",
    category: "Analysis",
    effectiveness: 0.86,
    avgLatency: "0.9s",
    avgTokens: 280,
    avgCost: "$0.0015",
    executions: 18750,
    lastUsed: "15 min ago",
    trend: "down" as const,
    pattern: "needs-optimization" as const,
  },
  {
    id: "prompt-005",
    name: "Email Draft Generator",
    agentName: "Communication Agent",
    traceId: "tr_email_001",
    category: "Communication",
    effectiveness: 0.79,
    avgLatency: "1.5s",
    avgTokens: 520,
    avgCost: "$0.0028",
    executions: 450,
    lastUsed: "2 days ago",
    trend: "stable" as const,
    pattern: "experimental" as const,
  },
  {
    id: "prompt-006",
    name: "Data Extraction",
    agentName: "Processing Agent",
    traceId: "tr_data_001",
    pattern: "high-performer" as const,
  },
];

// Trends Data for Charts
export const PROMPT_TRENDS = Array.from({ length: 14 }).map((_, i) => {
  const date = new Date("2024-01-01");
  date.setDate(date.getDate() + i);
  return {
    date: date.toLocaleDateString("en-US", { month: "short", day: "numeric" }),
    highPerforming: 12 + Math.floor(Math.random() * 5),
    lowPerforming: 3 + Math.floor(Math.random() * 3),
    avgLatency: 1200 + Math.floor(Math.random() * 300 - 150),
    avgTokens: 450 + Math.floor(Math.random() * 50),
  };
});

export const EVALUATION_METRICS = {
  workflow: {
    routingAccuracy: [
      { date: "Jan 01", score: 0.85 },
      { date: "Jan 03", score: 0.88 },
      { date: "Jan 05", score: 0.87 },
      { date: "Jan 07", score: 0.91 },
      { date: "Jan 09", score: 0.93 },
      { date: "Jan 11", score: 0.92 },
      { date: "Jan 13", score: 0.95 },
    ],
    completionRate: [
      { name: "Order Process", rate: 0.98 },
      { name: "Support Ticket", rate: 0.92 },
      { name: "Onboarding", rate: 0.88 },
      { name: "Refund", rate: 0.85 },
    ],
    scores: [
      { category: "Efficiency", score: 92 },
      { category: "Reliability", score: 88 },
      { category: "Speed", score: 85 },
      { category: "Cost", score: 78 },
    ],
  },
  agent: {
    toolUsage: [
      { name: "Vector Search", count: 1250 },
      { name: "SQL DB", count: 850 },
      { name: "Calculator", count: 420 },
      { name: "Weather API", count: 310 },
      { name: "Slack", count: 180 },
    ],
    toolSequence: [
      { sequence: "Search -> Summarize", count: 450 },
      { sequence: "SQL -> Format", count: 320 },
      { sequence: "Search -> Rerank -> Generate", count: 280 },
      { sequence: "Translate -> Email", count: 150 },
    ],
    metrics: [
      { metric: "Tool Selection", score: 0.94 },
      { metric: "Input Structure", score: 0.98 },
      { metric: "Error Recovery", score: 0.82 },
    ]
  },
  explainability: [
    { metric: "Faithfulness", score: 0.92, fullMark: 1 },
    { metric: "Context Relevance", score: 0.88, fullMark: 1 },
    { metric: "Answer Relevance", score: 0.91, fullMark: 1 },
    { metric: "Toxicity", score: 0.02, fullMark: 1 }, // Inverse (Low is good)
    { metric: "Bias", score: 0.05, fullMark: 1 }, // Inverse
  ]
};

// Evaluations Data
export const EVALUATIONS_DATA = [
  // Agent Evaluations
  {
    id: "agent-001",
    name: "Agent Decision Quality - Run #12",
    type: "agent",
    status: "passed" as const,
    score: 0.92,
    traces: 150,
    lastRun: "2 hours ago",
    criteria: "Decision accuracy, Response relevance, Task completion",
    feedback: "Agent consistently makes accurate decisions with high relevance scores.",
    evidence: "95% of agent decisions aligned with expected outcomes. Response time averaged 1.2s.",
    traceList: [
      { id: "tr_cs_001", name: "Customer Support - Login Issue", score: 0.95, status: "passed" },
      { id: "tr_cs_002", name: "Customer Support - Billing Query", score: 0.91, status: "passed" },
      { id: "tr_sum_001", name: "Document Summarization - Legal Contract", score: 0.89, status: "passed" },
    ],
  },
  {
    id: "agent-002",
    name: "Agent Decision Quality - Run #11",
    type: "agent",
    status: "passed" as const,
    score: 0.89,
    traces: 145,
    lastRun: "1 day ago",
    criteria: "Decision accuracy, Response relevance, Task completion",
    feedback: "Good performance with minor improvements in edge cases.",
    evidence: "89% accuracy rate. Some edge cases need refinement.",
    traceList: [
      { id: "tr_code_001", name: "Code Generation - React Component", score: 0.87, status: "passed" },
      { id: "tr_code_002", name: "Code Generation - API Endpoint", score: 0.91, status: "passed" },
      { id: "tr_sum_002", name: "Document Summarization - Research Paper", score: 0.89, status: "passed" },
    ],
  },
  {
    id: "agent-003",
    name: "Agent Response Time - Run #5",
    type: "agent",
    status: "warning" as const,
    score: 0.76,
    traces: 130,
    lastRun: "2 days ago",
    criteria: "Response latency, Processing speed, Efficiency",
    feedback: "Response times are acceptable but could be optimized.",
    evidence: "Average response time: 2.1s (target: 1.5s). 76% within SLA.",
    traceList: [
      { id: "tr_sent_001", name: "Sentiment Analysis - Product Review", score: 0.82, status: "warning" },
      { id: "tr_sent_002", name: "Sentiment Analysis - Customer Feedback", score: 0.71, status: "warning" },
      { id: "tr_data_001", name: "Data Extraction - Invoice Processing", score: 0.75, status: "warning" },
    ],
  },
  // Workflow Evaluations
  {
    id: "workflow-001",
    name: "Multi-Step Workflow - Run #8",
    type: "workflow",
    status: "warning" as const,
    score: 0.78,
    traces: 120,
    lastRun: "3 hours ago",
    criteria: "Step completion, Error handling, Flow efficiency",
    feedback: "Workflow completes successfully but has efficiency issues in step transitions.",
    evidence: "Average workflow completion time: 5.2s (target: 3.5s). 2 steps show bottlenecks.",
    traceList: [
      { id: "tr_cs_001", name: "Customer Support - Login Issue", score: 0.82, status: "warning" },
      { id: "tr_code_001", name: "Code Generation - React Component", score: 0.75, status: "warning" },
      { id: "tr_sum_001", name: "Document Summarization - Legal Contract", score: 0.77, status: "warning" },
    ],
  },
  {
    id: "workflow-002",
    name: "Multi-Step Workflow - Run #7",
    type: "workflow",
    status: "passed" as const,
    score: 0.85,
    traces: 115,
    lastRun: "1 day ago",
    criteria: "Step completion, Error handling, Flow efficiency",
    feedback: "Improved performance after optimization. All steps executing smoothly.",
    evidence: "Average completion time: 3.8s. 85% efficiency rate.",
    traceList: [
      { id: "tr_cs_002", name: "Customer Support - Billing Query", score: 0.88, status: "passed" },
      { id: "tr_code_002", name: "Code Generation - API Endpoint", score: 0.83, status: "passed" },
      { id: "tr_sum_002", name: "Document Summarization - Research Paper", score: 0.84, status: "passed" },
    ],
  },
  {
    id: "workflow-003",
    name: "Error Recovery - Run #3",
    type: "workflow",
    status: "passed" as const,
    score: 0.91,
    traces: 95,
    lastRun: "3 days ago",
    criteria: "Error detection, Recovery mechanisms, Fallback handling",
    feedback: "Excellent error recovery with minimal user impact.",
    evidence: "91% of errors recovered automatically. Average recovery time: 0.8s.",
    traceList: [
      { id: "tr_sent_001", name: "Sentiment Analysis - Product Review", score: 0.93, status: "passed" },
      { id: "tr_sent_002", name: "Sentiment Analysis - Customer Feedback", score: 0.89, status: "passed" },
      { id: "tr_data_001", name: "Data Extraction - Invoice Processing", score: 0.91, status: "passed" },
    ],
  },
  // Explainability Evaluations
  {
    id: "explain-001",
    name: "Decision Transparency - Run #15",
    type: "explainability",
    status: "passed" as const,
    score: 0.88,
    traces: 180,
    lastRun: "1 hour ago",
    criteria: "Reasoning clarity, Citation accuracy, Confidence scores",
    feedback: "Agent provides clear explanations with proper citations and confidence levels.",
    evidence: "88% of responses include detailed reasoning. All citations verified as accurate.",
    traceList: [
      { id: "tr_sum_001", name: "Document Summarization - Legal Contract", score: 0.91, status: "passed" },
      { id: "tr_sum_002", name: "Document Summarization - Research Paper", score: 0.87, status: "passed" },
      { id: "tr_code_001", name: "Code Generation - React Component", score: 0.86, status: "passed" },
    ],
  },
  {
    id: "explain-002",
    name: "Decision Transparency - Run #14",
    type: "explainability",
    status: "passed" as const,
    score: 0.86,
    traces: 175,
    lastRun: "1 day ago",
    criteria: "Reasoning clarity, Citation accuracy, Confidence scores",
    feedback: "Good transparency with minor improvements in citation formatting.",
    evidence: "86% clarity score. Citation accuracy at 94%.",
    traceList: [
      { id: "tr_cs_001", name: "Customer Support - Login Issue", score: 0.88, status: "passed" },
      { id: "tr_cs_002", name: "Customer Support - Billing Query", score: 0.84, status: "passed" },
      { id: "tr_data_001", name: "Data Extraction - Invoice Processing", score: 0.86, status: "passed" },
    ],
  },
  {
    id: "explain-003",
    name: "Confidence Calibration - Run #4",
    type: "explainability",
    status: "warning" as const,
    score: 0.73,
    traces: 160,
    lastRun: "2 days ago",
    criteria: "Confidence accuracy, Uncertainty quantification, Calibration",
    feedback: "Confidence scores need better calibration with actual accuracy.",
    evidence: "73% calibration score. Overconfidence detected in 18% of cases.",
    traceList: [
      { id: "tr_sent_001", name: "Sentiment Analysis - Product Review", score: 0.76, status: "warning" },
      { id: "tr_sent_002", name: "Sentiment Analysis - Customer Feedback", score: 0.71, status: "warning" },
      { id: "tr_email_001", name: "Email Draft - Partnership Proposal", score: 0.72, status: "warning" },
    ],
  },
  // RAG Evaluations
  {
    id: "rag-001",
    name: "Retrieval Accuracy - Run #10",
    type: "rag",
    status: "failed" as const,
    score: 0.65,
    traces: 200,
    lastRun: "30 min ago",
    criteria: "Context relevance, Answer accuracy, Source quality",
    feedback: "Retrieved context often lacks relevance. Needs improvement in chunk selection.",
    evidence: "Only 65% of retrieved chunks were relevant. Answer accuracy impacted by poor retrieval.",
    traceList: [
      { id: "tr_sum_001", name: "Document Summarization - Legal Contract", score: 0.62, status: "failed" },
      { id: "tr_sum_002", name: "Document Summarization - Research Paper", score: 0.68, status: "warning" },
      { id: "tr_data_001", name: "Data Extraction - Invoice Processing", score: 0.65, status: "failed" },
    ],
  },
  {
    id: "rag-002",
    name: "Retrieval Accuracy - Run #9",
    type: "rag",
    status: "warning" as const,
    score: 0.72,
    traces: 195,
    lastRun: "1 day ago",
    criteria: "Context relevance, Answer accuracy, Source quality",
    feedback: "Improved retrieval but still needs optimization for edge cases.",
    evidence: "72% relevance rate. Answer accuracy at 75%.",
    traceList: [
      { id: "tr_cs_001", name: "Customer Support - Login Issue", score: 0.74, status: "warning" },
      { id: "tr_cs_002", name: "Customer Support - Billing Query", score: 0.71, status: "warning" },
      { id: "tr_code_001", name: "Code Generation - React Component", score: 0.71, status: "warning" },
    ],
  },
  {
    id: "rag-003",
    name: "Context Quality - Run #6",
    type: "rag",
    status: "passed" as const,
    score: 0.84,
    traces: 185,
    lastRun: "2 days ago",
    criteria: "Chunk quality, Semantic relevance, Diversity",
    feedback: "Good context quality with diverse and relevant chunks.",
    evidence: "84% of chunks rated as high quality. Semantic relevance strong.",
    traceList: [
      { id: "tr_code_002", name: "Code Generation - API Endpoint", score: 0.86, status: "passed" },
      { id: "tr_sent_001", name: "Sentiment Analysis - Product Review", score: 0.83, status: "passed" },
      { id: "tr_sent_002", name: "Sentiment Analysis - Customer Feedback", score: 0.83, status: "passed" },
    ],
  },
];

// Helper functions
// Helper functions
export const getPromptStats = () => {
  const totalPrompts = PROMPTS_DATA.length;
  const highPerformers = PROMPTS_DATA.filter((p) => p.pattern === "high-performer").length;
  const avgEffectiveness =
    PROMPTS_DATA.reduce((sum, p) => sum + (p.effectiveness || 0), 0) / (PROMPTS_DATA.length || 1);
  const totalExecutions = PROMPTS_DATA.reduce((sum, p) => sum + (p.executions || 0), 0);
  const totalCost = PROMPTS_DATA.reduce(
    (sum, p) => sum + parseFloat((p.avgCost || "$0").replace("$", "")) * (p.executions || 0),
    0
  );

  return {
    totalPrompts,
    highPerformers,
    avgEffectiveness,
    totalExecutions,
    totalCost,
  };
};

export const getEvaluationStats = () => {
  const totalEvaluations = EVALUATIONS_DATA.length;
  const avgScore =
    EVALUATIONS_DATA.reduce((sum, e) => sum + (e.score || 0), 0) / (EVALUATIONS_DATA.length || 1);
  const passed = EVALUATIONS_DATA.filter((e) => e.status === "passed").length;
  const failed = EVALUATIONS_DATA.filter(
    (e) => e.status === "failed" || e.status === "warning"
  ).length;

  return {
    totalEvaluations,
    avgScore,
    passed,
    failed,
  };
};

// Get prompts by effectiveness for dashboard charts
export const getPromptsByEffectiveness = () => {
  return PROMPTS_DATA.sort((a, b) => (b.effectiveness || 0) - (a.effectiveness || 0)).slice(0, 4);
};

// Get evaluations by type for dashboard charts
export const getEvaluationsByType = () => {
  const types = ["agent", "workflow", "explainability", "rag"];
  return types.map((type) => {
    const evals = EVALUATIONS_DATA.filter((e) => e.type === type);
    const passed = evals.filter((e) => e.status === "passed").length;
    const total = evals.length;
    return {
      type,
      rate: total > 0 ? passed / total : 0,
      total,
      passed,
    };
  });
};
